# Generated by Django 2.1.3 on 2018-11-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risks', '0002_riskfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskFieldOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('risk_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='risks.RiskField')),
            ],
        ),
    ]
